spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity #MySQL connection jdbc url
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#  spring:
#    jpa:
#      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
